encoding: utf-8

# SEO相关信息
title: Two Blog
description: 世事洞明皆学问，人情练达即文章。
keywords: foobar
author: Two
footerText: https://aineer.github.io

# 这些不要动
permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: ['CNAME', 'README.md', 'LICENSE', '_site', 'dist', 'Gemfile', 'Gemfile.lock', 'blog.sh']



# 留言配置, 不需要的话值设置为空，同时删除 # 菜单 配置项中的留言页面
# 官网 https://www.bmob.cn
# 文档 https://bmob.github.io/hydrogen-js-sdk
# 建议自己申请一个，表结构如下
# 表名 Comment ,字段如下
# url      String
# time     Date
# nickName String
# email    String
# content  String
# website  String
bmobApplicationId: 34f0386ac5bd50fd77fe82190af00faf
bmobRestApiKey: 6f1419c800083315432f2df7dcb503d4



# 域名配置
# baseurl配置,如果网站部署在根目录下的其他目录中，请设置为 /目录名
domainUrl: ''
baseurl: ''

# 吐个槽地址，会在chat页面中重定向到该地址
tucaoUrl:

# 菜单
# 必填字段 title: '文本' url: '链接'
# 可选字段 target: '_blank' 新页面打开 
menu:
  - title: 首页
    url: /
  - title: 归类
    url: /pages/categories.html
  - title: 搜索
    url: /pages/search.html
  - title: 友链
    url: /pages/links.html
  - title: 留言
    url: /pages/chat.html
  - title: 关于
    url: /pages/about.html

# 点击页面文字冒出特效,不需要请设置为false
extClickEffect: false

# Google Adsense,不需要请设置为false
# _includes/ext-adsense.html 里面修改为自己的配置
extAdsense: false

# 数学公式支持，比较影响加载速度,不需要请设置为false
extMath: false

# 显示访问量统计，由不蒜子提供服务
extCount: false

# 友情链接
links:
  # - title: xxx
  #  url: https://www.foobar.com

  - title: Two Blogger
    url: https://fossusera.blogspot.com
    desc: Two 的小天地
  - title: 一把江湖刀
    url: https://jianghudao.top
    desc: 江湖刀的博客
